# Generated by Django 4.2.7 on 2023-11-12 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0003_item_region_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.CharField(choices=[('Вінницька область', 'Вінницька область'), ('Волинська область', 'Волинська область'), ('Дніпропетровська область', 'Дніпропетровська область'), ('Донецька область', 'Донецька область'), ('Житомирська область', 'Житомирська область'), ('Закарпатська область', 'Закарпатська область'), ('Запорізька область', 'Запорізька область'), ('Івано-Франківська область', 'Івано-Франківська область'), ('Київ', 'Київ'), ('Київська область', 'Київська область'), ('Кіровоградська область', 'Кіровоградська область'), ('Луганська область', 'Луганська область'), ('Львівська область', 'Львівська область'), ('Миколаївська область', 'Миколаївська область'), ('Одеська область', 'Одеська область'), ('Полтавська область', 'Полтавська область'), ('Рівненська область', 'Рівненська область'), ('Сумська область', 'Сумська область'), ('Тернопільська область', 'Тернопільська область'), ('Харківська область', 'Харківська область'), ('Херсонська область', 'Херсонська область'), ('Хмельницька область', 'Хмельницька область'), ('Черкаська область', 'Черкаська область'), ('Чернівецька область', 'Чернівецька область'), ('Чернігівська область', 'Чернігівська область')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='item.item')),
            ],
        ),
    ]
